# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "google" { 
    credentials = "/home/wlados/.gcp/terraform.json"
    project = "helical-history-342218"
    region  = "us-central1"
    zone    = "us-central1-a"
}

